{{- if .Values.airflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "starlake.fullname" . }}-airflow
  labels:
    {{- include "starlake.componentLabels" (dict "component" "airflow" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.airflow.webserver.service.type }}
  ports:
  - name: http
    port: {{ .Values.airflow.webserver.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "starlake.componentSelectorLabels" (dict "component" "airflow" "context" .) | nindent 4 }}
{{- end }}
