{{- if .Values.gizmo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "starlake.fullname" . }}-gizmo
  labels:
    {{- include "starlake.componentLabels" (dict "component" "gizmo" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.gizmo.service.type }}
  ports:
  - port: {{ .Values.gizmo.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "starlake.componentSelectorLabels" (dict "component" "gizmo" "context" .) | nindent 4 }}
{{- end }}
